hyw/feat/user/OneMenuRead
KioSSGk/kiossgk pull request #140
Opened 2024-08-09 05:52 UTC by 10wook

fix #59 

연결해두었고, 수정하여 옵션이 뜨게 만들어야 합니다.

2024-08-09 05:52 UTC, SugarRaccoon commented
확인 완료 하였습니다

2024-08-09 05:56 UTC, leedonguk0809 requested changes
퍼블릭 있는거 지워주세요

2024-08-09 05:59 UTC, leedonguk0809 approved these changes
확인 했습니다

2024-08-09 06:00 UTC, SugarRaccoon approved these changes
퍼블릭에 있는 파일 지운거 확인했습니다

2024-08-09 06:04 UTC, merged

2024-08-13 05:58 UTC, 10wook commented
fix #101 
원래 #59 이슈였으나
위 101이슈도 함께 해결하였습니다.